name: connect_umadim_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.1
  google_fonts: ^6.2.1
  flutter_riverpod: ^2.6.1
  loading_indicator: ^3.1.1
  mask_text_input_formatter: ^2.9.0
  brasil_fields: any
  intl: any
  firebase_auth: ^5.4.1
  cloud_firestore: ^5.6.2
  freezed_annotation: ^2.4.4
  dartz: ^0.10.1
  dropdown_textfield: ^1.2.0
  lottie: ^3.3.1
  flutter_svg: ^2.0.17
  image_picker: ^1.1.2
  supabase_flutter: ^2.8.3
  persistent_bottom_nav_bar: ^6.2.1
  shimmer: ^3.0.0
  cached_network_image: ^3.4.1
  uuid: ^4.5.1
  flutter_localizations:
    sdk: flutter
  table_calendar: ^3.1.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/animations/
    - assets/icons/
