// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDi5xRoUJ9fzGZImmqy4rLEBfURUd939TA',
    appId: '1:503594139897:web:c677159b4827d3a45a2228',
    messagingSenderId: '503594139897',
    projectId: 'conecta-umadim',
    authDomain: 'conecta-umadim.firebaseapp.com',
    storageBucket: 'conecta-umadim.firebasestorage.app',
    measurementId: 'G-5ME86870M4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCi5tetdQuEDxHntluMf47JuUp9M9EagY',
    appId: '1:503594139897:android:dd95eefc93fecd6e5a2228',
    messagingSenderId: '503594139897',
    projectId: 'conecta-umadim',
    storageBucket: 'conecta-umadim.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBSReard9a6Xe47aXxZibBRUwU3xCSNuuw',
    appId: '1:503594139897:ios:02a0cbdb2faea2195a2228',
    messagingSenderId: '503594139897',
    projectId: 'conecta-umadim',
    storageBucket: 'conecta-umadim.firebasestorage.app',
    iosBundleId: 'com.example.connectUmadimApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBSReard9a6Xe47aXxZibBRUwU3xCSNuuw',
    appId: '1:503594139897:ios:02a0cbdb2faea2195a2228',
    messagingSenderId: '503594139897',
    projectId: 'conecta-umadim',
    storageBucket: 'conecta-umadim.firebasestorage.app',
    iosBundleId: 'com.example.connectUmadimApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDi5xRoUJ9fzGZImmqy4rLEBfURUd939TA',
    appId: '1:503594139897:web:9d0e8085ceb534eb5a2228',
    messagingSenderId: '503594139897',
    projectId: 'conecta-umadim',
    authDomain: 'conecta-umadim.firebaseapp.com',
    storageBucket: 'conecta-umadim.firebasestorage.app',
    measurementId: 'G-YYTDLG999P',
  );
}
